### ISSUE TITLE
SERVER_ERROR object too large for cache

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1058]
Seen `level=error ts=2018-10-04T01:14:43.381776392Z caller=memcached.go:225 msg="failed to put to memcached" err="memcache: unexpected response line from \"set\": \"SERVER_ERROR object too large for cache\\r\\n\""` in the query-frontend logs.

**Comment by tomwilkie** [comment]
Would be good to export a historgram of sizes, and ensure our metrics for capturing the memcache errors are working.  

Also, we're compressing these results - I'm surprised they're >1MB.  Might be worth checking its reasonable data and we're not leaking or corrupting the datastructure somehow.

**Comment by nrjpoddar** [comment]
We see a lot of these error messages too, specially after enabling index caching. Is the recommendation to have 2 separate memcached(s) for chunk & index caching?

**Comment by tomwilkie** [comment]
We run 4 caches - chunks, index reads, index writes and query results. I’d
recommend it, yeah. There’s a memcached mixin somewhere too.

**Comment by nrjpoddar** [comment]
Interesting, I will look for the mixin (also if you can share a link, that would help). I understand separating chunks & indexes, what's the added benefit of separating out index write & read?
I haven't looked at the code but can you explain why that's the case? Additionally, is index write primarily used by ingesters?

**Comment by tomwilkie** [comment]
> Interesting, I will look for the mixin (also if you can share a link, that would help

Oh I realised I didn't actually open source it, so I just stuck it here: https://github.com/grafana/jsonnet-libs/pull/110

> I understand separating chunks & indexes, what's the added benefit of separating out index write & read?

They store different things for different purposes, the IO patterns on the two caches are very different; and the retention is completely difference.  Whats more one is on the read path and one is on the write path.  I find it easier to separate and scale them (#pods, CPU, memory and item size) separately.

**Comment by nrjpoddar** [comment]
@tomwilkie We have implemented separate memcaches for chunks, index read & index write but we still this message a lot: 
`cortex-cortex-querier-5f6db95bc4-scchx querier level=error ts=2019-03-05T18:26:21.056321503Z caller=memcached.go:230 msg="failed to put to memcached" name=store.index-cache-read. err="memcache: unexpected response line from \"set\": \"SERVER_ERROR object too large for cache\\r\\n\""`

Because of this issue our query latencies are really high as the querier is constantly hitting the DynamoDB index table.

Is there a reason why index caches should be using more than 1 MB per memcache object (the default setting). I'm seeing that the memory consumed by index read memcache is very low (in MBs)

**Comment by nrjpoddar** [comment]
Update: I fixed this issue by adding the option `-I 32m` to the memcached for index reads. I'm still unclear as to why we need larger than 1 MB for index read caches.

**Comment by bboreham** [comment]
The biggest index rows have all timeseries for a metric for a day. 
Suppose each entry is 100 bytes and there are 100,000 timeseries under a metric - that’s 10MB. The data is compressed but still 1MB is not unexpected. 

The v10 schema PR shards those rows to give smaller results but more index lookups.

**Comment by nrjpoddar** [comment]
Thanks @bboreham for the explanation. I will keep it at `32m` for now, will tune it by looking at long term usage.
