### ISSUE TITLE
Buffered datapoints returned after last sample has been pushed

### ISSUE THREAD

**Issue by rsteneteg** [cortexproject/cortex#1276]
When datapoints for a time series stops being pushed, Cortex will continue to return the last datapoint for additional time period (the full lookback delta) even if no sample was pushed to Cortex during that window.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/1894640/54256151-087e9580-4529-11e9-8d38-f75fd1f5bc4e.png">

In the above picture I pushed 1 sample to Cortex at 13:43:15, yet it returned 8 datapoints over a 2m period (I currently have the lookback delta set to 2m, if I use the default lookback Cortex returns datapoints for 5m instead).

Since I only pushed in 1 sample I would have thought I would only see 1 datapoint.

By looking at the code it is the BufferedSeriesIterator in the Prometheus code that returns these extra datapoints, since it uses the lookback delta here https://github.com/cortexproject/cortex/blob/master/vendor/github.com/prometheus/prometheus/storage/buffer.go#L79

I did a quick look at the code in Prometheus master as well and they look similar, yet if I make Prometheus scrape 1 sample, Prometheus will only return datapoints for the duration of the Prometheus scrape interval (not the full lookback delta).

**Comment by rsteneteg** [comment]
FYI @khaines

**Comment by rsteneteg** [comment]
It seems like Prometheus advances the Buffered iterator here https://github.com/prometheus/prometheus/blob/master/storage/buffer.go#L97, while Cortex don't

**Comment by tomwilkie** [comment]
Thanks the the report @rsteneteg! I'm wondering if this has to do with staleness handling.  When you say "if I make Prometheus scrape 1 sample, Prometheus will only return datapoints for the duration of the Prometheus scrape interval" how did you achieve this?  Because if you removed the target or series, I believe Prometheus inserts a special "end of timeseries" marker.

Cortex should honor them, if they get propagated.  But if they don't, if will fall back to the legacy behaviour and return the old value for the staleness period.

**Comment by rsteneteg** [comment]
As metrics flows through my metrics pipeline they pass through a custom prometheus exporter that I built that will remove all metrics after it has been scraped, similar to how the blackbox exporter works by rebuilding the prometheus registry for each scrape.

I found last night that Cortex uses the `concreteSeriesIterator`, while prometheus uses a different iterator called `chunkSeriesIterator` which seems to behave differently

**Comment by rogst** [comment]
I modified the Cortex `concreteSeriesIterator` to behave the similar to the Prometheus iterator in that it would return a NaN marker if there is no more samples. But I needed to hardcode the step interval in the iterator which it would need to get dynamically for it to be usable.
The timestamp on the NaN marker needs to be between one step ahead of the last sample for it to work, Prometheus gets that timestamp naturally since the NaN is added during the Scrape.

**Comment by rogst** [comment]
See PR #1310

**Comment by rogst** [comment]
Added a configurable duration for how long after the last sample within the lookback period to add the NaN end marker, similar to what Prometheus does for series that is removed from a scrape target. Since Cortex does not scrape we need to configure how soon after the NaN value should be.

The EndMarkerDelta should be set to the lowest query step size you want to use.

The behavior is that the BufferedSeriesIterator will fill in missing samples using the previous sample up until the last real sample within the lookback delta.

**Comment by rogst** [comment]
I was using a custom application doing remote writes to Cortex which did not send NaN values when the metrics should stop, and was instead trying to do sparse push based writes.

When using Prometheus remote writes which sends NaN to terminate time series, Cortex did not add any trailing data points.

This issue can be closed.
