### ISSUE TITLE
Use prometheus/tsdb & write blocks to object store.

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1323]
@gouthamve had a short design doc that he can add.

The idea is to use prometheus/tsdb in the ingester. This will allow us to:
- More closely track upstream and eventually delete a bunch of code.
- Store more data in the ingesters without OOMing them, as it will persist to local disk.
- Write large blocks (containing chunks for many series) to the object store, reducing TCO.
- As we'll now have large blocks in object store, things like compaction and deduping become cost effective and feasible.

**Comment by tomwilkie** [comment]
Found it: https://docs.google.com/document/d/1Uiu5nE1BmiAjfUXgX5ytq_5u7lRK5OspjMUX7ki_aQc/edit

**Comment by mizeng** [comment]
May I ask what's the status of this idea? Did you abandon this with some bottlenecks of current design or performance?

**Comment by pracucci** [comment]
> May I ask what's the status of this idea? Did you abandon this with some bottlenecks of current design or performance?

We currently have an experiment support for the [blocks storage](https://cortexmetrics.io/docs/operations/blocks-storage/), based on Prometheus TSDB and Thanos (mainly the Thanos shipper and bucket store).

_I'm going to close this issue since, even if not production-grade, the features described in the issue are already supported._
