### ISSUE TITLE
Idea: Add HTTP endpoint to show overrides.

### ISSUE THREAD

**Issue by tomwilkie** [cortexproject/cortex#1324]
Like /ring, /user_stats etc.

**Comment by bboreham** [comment]
Should be quite similar to the `/config` endpoint.

**Comment by ethervoid** [comment]
Hi! First contributor attempt here!

Do you mind if I take this one as my first issue?

Thank you

**Comment by pstibrany** [comment]
> Hi! First contributor attempt here!
> Do you mind if I take this one as my first issue?

Not at all, please go ahead, and thank you!

**Comment by ethervoid** [comment]
Hi again!

I have some questions about this task to understand it better.

My first question is what is the expected output for the endpoint. My idea is to show a table with the different overrides for the different tenants but I want to confirm that.

Another question is about passing or gathering the overrides. 

I've been taking a look at the code, first time using/viewing cortex, and I've seen there is no "quick" way to gather the overrides per user [unless I know the user](https://github.com/cortexproject/cortex/blob/master/pkg/util/validation/limits.go#L416). 

My first option was to include a new endpoint in the [RegisterAPI](https://github.com/cortexproject/cortex/blob/master/pkg/api/api.go#L169-L175) and use the `t.Overrides` struct but that's not possible because:

- The initialization of overrides is after the API
- The overrides struct doesn't allow to get the raw limits information to show it.

I don't know if it's possible to get that information from the Config object but my idea is to register a new overrides endpoint [here](https://github.com/cortexproject/cortex/blob/master/pkg/cortex/modules.go#L170-L175) where I can get the `map[string]*validation.Limits` from the `t.RuntimeConfig` and iterate through that object to display the values but I'm not sure if that is the best approach or even if that is what is asked for, to be honest.

Thank you!

**Comment by bboreham** [comment]
I think it would be fine as a first step to show overrides for a single user.

I didn't follow what you meant about endpoints - could you take a look at how `user_stats` is implemented?
Main code is here: https://github.com/cortexproject/cortex/blob/8460a8871c7387f5bffc04f878f0815487465eca/pkg/distributor/http_admin.go
and http handler is added here: https://github.com/cortexproject/cortex/blob/8460a8871c7387f5bffc04f878f0815487465eca/pkg/api/api.go#L307

There is an `all_user_stats` path which might show an interesting contrast.

(BTW hit `t` in GitHub to get a URL against a specific commit, so it will still point to a valid place after the code has evolved)

**Comment by pracucci** [comment]
A previous comment states:
> Should be quite similar to the /config endpoint.

I was expecting the overrides endpoint to just marshal (in YAML) the overrides and return it, like we do in `/config`. Ideally, the overrides endpoint should provide an easy way to get back the YAML overrides. Am I missing anything?

**Comment by bboreham** [comment]
That's probably a better idea.

@ethervoid let us know if you need pointers to how `/config` is implemented.

**Comment by ethervoid** [comment]
@pracucci @bboreham Thank you very much for your help!

I'll try to return the YAML of the overrides as suggested :)

**Comment by ethervoid** [comment]
@bboreham I've sent a PR for this issue. Do I have to notify or include people as reviewers in any form?

Thank you!
