### ISSUE TITLE
Statsd storage?

### ISSUE THREAD

**Issue by pablokbs** [cortexproject/cortex#1503]
Hello! Is there a way to use cortex as a statsd server also? I'm looking to integrate all of our metrics into one system, and I would like to use cortex to store my statsd metrics

Thanks

**Comment by jtlisi** [comment]
Cortex does not currently implement the statsD write protocol, and it is unlikely it will do so in the future. If you want to use statsd to aggregate and store data in cortex that is possible. You would have to write a backend for statsd that writes metrics to cortex using the prometheus remote write format.

The code that you can take inspiration from to implement that can be found here: https://github.com/prometheus/prometheus/tree/release-2.11/storage/remote

If you are sold on statsd and want to implement cortex as a backend, that is possible. However, using prometheus to write metrics to cortex is optimal. Especially since cortex uses PromQL for queries and the majority of the cortex community also uses Prometheus.

**Comment by pablokbs** [comment]
Thanks for the response. Yeah I understand that Prometheus is the right choice but we still have some legacy services using statsd, we will look into that. Thanks
