### ISSUE TITLE
Consider allowing metric relabelling (or just "drop") during ingest

### ISSUE THREAD

**Issue by csmarchbanks** [cortexproject/cortex#1507]
I think a nice feature would be to provide a way to use metric relabelling in the distributors.

The main use case I want is to be able to turn off certain sources of metrics quickly without having to change the remote write config of the prometheus instances running in each of my clusters.

**Comment by bboreham** [comment]
I've certainly wanted to filter out certain metrics before they get to the ingester, either because they are high-cardinality or just bogus.

However I find the Prometheus metric relabel syntax extremely convoluted.  How about a PromQL match clause that would filter out, e.g. `{__name__="container_tasks_state"}`?

**Comment by tomwilkie** [comment]
+1 this seems like it would be useful.  We'd want to be able to specify multiple matchers, and do it per user, but that shouldn't be difficult.

**Comment by csmarchbanks** [comment]
This is a possible implemntation of  #771

**Comment by bboreham** [comment]
Related: #2068
