### ISSUE TITLE
separate PromQL's parse from its func/aggr calculation

### ISSUE THREAD

**Issue by jiacai2050** [cortexproject/cortex#1573]
It seems Cortex is no difference with Thanos, just a long-term storage engine backend.

What I recently want is to separate PromQL's parse from its func/aggr calculation, push down to underlying storage, leverage storage's distributed computing with PromQL's rich expression. Is there any project working on this ?
Will Cortex support this?

**Comment by bboreham** [comment]
Are you asking how a single Prometheus query can be distributed across multiple processes to take advantage of multiple machines to execute on?

Cortex can split queries by time, typically by day, and execute those pieces in parallel.  Since the storage is also split by day this gives decent distribution.

There has been some work to look at splitting queries in other ways: https://docs.google.com/document/d/1Phv74bMp7MjNhlmIoxDp2kSqykOzT4YmJvng4EeBk0M

**Comment by jiacai2050** [comment]
@bboreham My question is similar to Proposal I in the google doc you link.

In prometheus's remote query, there is a `storage.SelectParams` which contains a `Func` field, but isn't used, I asked this in [google group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/prometheus-users/leIVTVPVqhQ/B3zGFHGXAQAJ), and is implementing this feature in a tsdb designed within my company.

**Comment by bboreham** [comment]
Ok; shall we close this issue then?

**Comment by jiacai2050** [comment]
What's the progress of Proposal I? Maybe I can participate with this.

**Comment by gouthamve** [comment]
Hi, I am closing this issue as we have more concrete ways of how to do this:
https://github.com/cortexproject/cortex/issues/1796 and https://github.com/cortexproject/cortex/pull/1730

If you think there are more ways of achieving the same, please feel free to reopen this.
