### ISSUE TITLE
Keep docs up to date

### ISSUE THREAD

**Issue by albertdb** [cortexproject/cortex#1643]
Hi,

I think it would be good for the project, as for any software project in general, to keep existing docs (which are not as many as an adopter would desire, but that's another story) and config files up to date with changes, new features or recommendations.

For example, I see on changelog that there are new command-line parameters which would be good to use, but going to `docs/arguments.md` shows nothing about them.

In general, most/many of the pull request come without changes in docs and they get approved, which is quite worrying.

Thanks

**Comment by bboreham** [comment]
While I appreciate your frustration, I don't think this will do any good as an issue - we don't read them at the time that matters.

Is it possible the information you were looking for is in #1622 ?

**Comment by albertdb** [comment]
Actually it is, but this is more about setting guidelines/templates for PRs and the like, e.g. having to tick "have you updated docs?" checkbox when submitting PR. That would help, I think.

This looks to be an awesome project, but the lack of documentation almost made me discard it as an option for Prometheus persistence.

Just as an example, there's nowhere a document explaining what are or what to do with the bunch of yaml for Kubernetes available in cortex/k8s. One could figure out, but a document about it would save adopters hours of guesses.

**Comment by friedrich-at-adobe** [comment]
@albertdb (I am not a maintainer)  IMHO The first thing to try when coming to cortex is to run it in your machine without any extra components.

Like explained here:
https://github.com/cortexproject/cortex/blob/master/docs/getting_started.md

If you do that you learn about the many different flags that you can use and you can start adding components as you see fit (And understand them)

Moving from single process to kubernetes is something that is entirely depending on everyone's ability. Rolling out on kubernetes is more than just applying manifests. I am sure you know that.

And moving forward to production quality It is very assumed here that certain technology is understood: kubernetes, prometheus, consul, etcd, memcached, dynamodb, cassandra, s3, etc and even golang so you can read the source code. 

Yes, the source must be read very early and it's quite understandable if you have some golang experience.

Documenting all the details of all the possible dependencies won't help adopters. It will make the way harder for current users because of the docs redundancy.
