### ISSUE TITLE
Better schema documentation and examples

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#1783]
I've noticed a common issue among new users operating Cortex. They seem to not understand the schema configs they are using and are deploying flags that are probably not necessary.

#1646 and #1769 for example. Both of these users are using flags instead of a schema config file. They are all defining flags for multiple schemas when as new users they should not bother defining configs for legacy schemas.

I think this points to a general lack of documentation/examples for schema configs in Cortex and something we should look into improving.

Related issues:
#1731 
#1646 
#1769

**Comment by pracucci** [comment]
A note about how this issue relate to the recent `make doc` tool:

We recently merged the PR #1952 to automatically generate the [config file reference documentation](https://cortexmetrics.io/docs/configuration/configuration-file/) but this does *not* include the schema config file documentation. Due to its nature, the tool can't be used to extract the schema config. Moreover, the schema config requires an extensive descriptive documentation, being non trivial to understand.

**Comment by pracucci** [comment]
@gouthamve Should we consider this done?

**Comment by gouthamve** [comment]
https://cortexmetrics.io/docs/configuration/schema-configuration/ I'd say yes
