### ISSUE TITLE
Pre Golang-CI Linting Errors

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#1912]
With Cortex moving to golang-ci (#1853) as things stand there are a large number of issues being detected by the linter. We should look into rectifying those errors. These errors will not affect CI because #1853 will not throw an issue for errors that existed before it was merged.

**Comment by bboreham** [comment]
I fixed all the ones reported in #1853.  Perhaps this issue relates to the ones in the code from before?

**Comment by jtlisi** [comment]
@bboreham Yea all of the linting issues from before.

**Comment by nrchakradhar** [comment]
@jtlisi @bboreham Where can I find the list of errors so that I can attempt to fix them? Thanks

**Comment by pracucci** [comment]
@nrchakradhar Instead of manually spotting linting issues, you may just want to run `make lint` locally editing the `Makefile` to remove `--new-from-rev ed7c302fd968`. You may end up with many issues to fix; if you will work on this, could be wise to split the fixes into multiple PRs, in order to facilitate the reviewers' work.

**Comment by nrchakradhar** [comment]
@pracucci I will try running locally and see.

**Comment by zendern** [comment]
@nrchakradhar i just opened a PR to fix almost all the issues. I would have commented sooner but was on a plane. Take a look if you are interested or have any feedback.
