### ISSUE TITLE
Zone awareness: Support less zones than replication factor

### ISSUE THREAD

**Issue by weeco** [cortexproject/cortex#2351]
**Usecase**
@khaines recently added zone awareness (https://github.com/cortexproject/cortex/pull/2317/files) which has the limitation that you must run Cortex in at least n different availability zones where n is the replication factor (default 3). 

I don't want to run 3 AZ (availability zones) because that means even more interzone traffic compared to running it in just 2 AZ. Additionally I have enough trust in my cloud provider that I only want to protect against an outage of **one** AZ and not two.

At the same time I don't want to lower the replication factor from 3 to 2, because here and there ingesters have crashed in the past. Therefore I feel more comfortable having 2 backups instead of just one.

**Feature request**
Support less zones than replication factor for zone awareness. That obviously requires reusing a zone in case one runs Cortex in 2 AZ and has a replication factor of 3.

**Comment by khaines** [comment]
This seems like an anti-pattern IMO and it should be something avoided with the AZ aware writes.

AZ aware writes make the strong guarantee that it will not put more than 1 replica in a given zone. This makes it so you can lose 1-N nodes in a single AZ without interruption. Prior to this with 3 replicas you could just have 1 node go offline without possible interruption. Once there were 2 nodes offline there was a chance that some time-series would be missing 2/3 of their replicas and the write would fail. 

If we reconfigure AZ aware writes to "fall back" to writing within an already used zone, it is effectively turning off the feature, because it cannot guarantee anything about the AZ's anymore. The moment 2 nodes in an AZ are offline or impacted writes could begin to fail because they could have 2/3 replicas for a time-series. 

If you want to effectively protect against losing an AZ in your cloud provider, then you should be running across 3 AZ's, not 2 when using a majority available write & read system like the ingesters. In your current setup, you will experience impacts to your writes & reads if an AZ goes offline with or without the AZ aware writes.

**Comment by weeco** [comment]
> Once there were 2 nodes offline there was a chance that some time-series would be missing 2/3 of their replicas and the write would fail.

@khaines Can you explain why writes would fail if 2 of 3 the ingester replicas are offline?

**Comment by khaines** [comment]
Cortex requires that a majority quorum of ingesters for a particular token are available in order for a write (or query) to succeed.  The particular logic involved can be found in [replication_strategy.go](https://github.com/cortexproject/cortex/blob/master/pkg/ring/replication_strategy.go#L14), but in summary, there needs to be (replication_factor/2)+1 ingesters available for an operation to be a success. So with a replication factor of 3, there needs to be 2 ingesters available; which is why losing 2/3, leaving just 1 will cause errors.

**Comment by weeco** [comment]
Thanks for the explanation. Agreed, this would be an antipattern then.
