### ISSUE TITLE
Improve Remote API documentation: `api/v1/prom/push`

### ISSUE THREAD

**Issue by gotjosh** [cortexproject/cortex#2389]
Based on a conversation from https://github.com/cortexproject/cortex/pull/2383

At the moment, it is not clear what is the lifecycle of a `WriteRequest` when pushed to `api/v1/prom/push`:

- Which errors are reported; Assuming ~~#2383 is merged~~ (got merged 😄), we only send back the first error we encounter when processing samples.
- How sample distribution/ingestion works; Samples are validated before distribution. The ones that do not pass validation are simply discarded, and the ones that do pass are processed. If a failure occurs on ingestion (e.g. duplicated timestamp+value) there are multiple scenarios to cover too.

Would we like to cover these?

**Comment by pracucci** [comment]
> we only send back the first error we encounter when processing samples.

I would also explain the returned error is a 400, so that Prometheus does not resend the request but still Cortex signals back to Prometheus that some series have not been successfully ingested.

> How sample distribution/ingestion works; Samples are validated before distribution

This is briefly explained in the architecture page (but not in details). We also reference some validation config options in `arguments.md`.

**Comment by pracucci** [comment]
_Still valid_
