### ISSUE TITLE
How to configure distributor.replication-factor

### ISSUE THREAD

**Issue by storyicon** [cortexproject/cortex#2622]
Hello, I started to contact cortex last week. I may not know enough about the project, so have some doubts:
How to configure `distributor.replication-factor`? should this parameter be equal to the number of real replica number of ingester?

**Comment by pracucci** [comment]
👋  @storyicon 

The replication factor is the number of different ingesters to which a single received series should be replicated. It's should *not* be set to the number of total ingester replicas, but to the number of ingester replicas to which a single series should be replicated to.

In the real world there are mainly two settings:
- Replication factor = `1`: no replication. If an ingester is lost, you will loose all series still kept into that ingester's memory (basically all series not flushed to the long-term storage yet)
- Replication factor = `3`: replicate each series across 3 ingesters. Write quorum is 2. If you loose an ingester, then you get no data loss and the ingestion still continue to work (because quorum is 2).

**Comment by storyicon** [comment]
I'm pleasantly surprised that you made such a detailed answer for a beginner like me, thank you very much @pracucci 
Recently I have spent more time researching Cortex, this is a great project, I hope I will be able to make some contributions to it later, at the same time I am preparing to promote it in our company.

**Comment by ssesha** [comment]
Hi @pracucci I am new to cortex and found this issue really helpful in understanding the replication across ingesters. I have some doubts regarding what happens when an ingester is lost when i have replication factor 3 and 3 ingesters. Are the lost series replicated again when a new ingester comes up or do some series stay at 2? If they are indeed replicated again how do I track this behaviour and know it has successfully completed? Any metrics to watch?

**Comment by pracucci** [comment]
> Are the lost series replicated again when a new ingester comes up or do some series stay at 2?

It depends whether the WAL is in use or not. If you running the chunks storage, the WAL is optional (disabled by default), while if you run the blocks storage the WAL is always in use.

When **WAL is used**, the new ingester is expected to be started up with the same disk of the terminated one. If so, the WAL will be replayed and all time series data recovered, so you will get back to 3 replicas for each series data point (sample).

When **WAL is not used**, the new ingester will start empty and so for the data that was in the lost ingester there will only be 2 replicas.

**Comment by ssesha** [comment]
Thank you so much for making things clear @pracucci. I am currently not using wal and running chunks storage, so will keep this in mind. Decided we should try out Cortex in our org (vs Victora and M3db) for the tech and the helpful community. Your prompt and detailed answer just reinforced my decision. Onwards!
