### ISSUE TITLE
Reuse ring memberlist client in Alertmanager

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#2650]
In order to run the alertmanager in a single binary the user will have to run two separate gossip ports. One for the alertmanager and another for the ring kv client. We should explore reusing the the ring memberlist implementation in place of the alertmanager cluster implementation.

**Comment by pracucci** [comment]
@pstibrany Isn't reusing the ring client something we already did for other components?

**Comment by pstibrany** [comment]
> @pstibrany Isn't reusing the same memberlist client something we already did for other components?

My understanding of this issue is different. Our existing work in Cortex allowed to use single memberlist-based between different components.

What I believe Jacob describes here is that AlertManager itself uses memberlist library to setup a cluster (with AM nodes). I think Jacob proposes to use Ring for AlertManagers instead, which would allow it to use our memberlist-based Ring implementation as well.
