### ISSUE TITLE
Some doubts about the range comparison of blobs in the index query

### ISSUE THREAD

**Issue by storyicon** [cortexproject/cortex#2737]
Hello, I have some doubts when I try to do some query optimization on cortex. When I checked the Cassandra CQL executed by Cortex, I found the following execution statement：

```
SELECT count(*) FROM index_18430 WHERE hash = ? AND range >= ? AND value = ? ALLOW FILTERING
```

I don’t quite understand the logic of `range >= ?`, because the range value I retrieved in the query condition is just the hash of the value：

https://github.com/cortexproject/cortex/blob/b4b3ebcd6d3c127884ede8eb70cfbadcabe7e37a/pkg/chunk/schema.go#L853

The `RangeValue` in the index table is generated by `hash(Value, seriesID)`:
https://github.com/cortexproject/cortex/blob/b4b3ebcd6d3c127884ede8eb70cfbadcabe7e37a/pkg/chunk/schema.go#L799

What's the point of comparing ranges on a bunch of bytes? Or is this just a trick for using indexes?

I separately execute queries with and without range conditions, and the result set looks the same:
```
cqlsh:cortex> SELECT count(*) FROM index_18430 WHERE hash = 'fake:d18430:node_cpu:job' AND range >= textasblob('qLgTnGpKJxOu9Fx+iPCOWMpsJRWYTDAz854l3Z7uGp8') AND value = textasblob('node_exporter') ALLOW FILTERING;

 count
---------
 1485893
cqlsh:cortex> SELECT count(*) FROM index_18430 WHERE hash = 'fake:d18430:node_cpu:job' AND value = textasblob('node_exporter') ALLOW FILTERING;

 count
---------
 1485893
```
```
cqlsh:cortex> SELECT count(*) FROM index_18430 WHERE hash = 'fake:d18430:node_cpu:instance_name' AND range >= textasblob('p/ZVRRQIX5Oqa3TP47j6I4i99Rzi7shMRV1NHUX/zII') AND value = textasblob('shylf-ops-docker-slb-34') ALLOW FILTERING;

 count
-------
   311

cqlsh:cortex> SELECT count(*) FROM index_18430 WHERE hash = 'fake:d18430:node_cpu:instance_name' AND value = textasblob('shylf-ops-docker-slb-34') ALLOW FILTERING;

 count
-------
   311
```

Can someone explain this?

**Comment by pstibrany** [comment]
Idea behind https://github.com/cortexproject/cortex/blob/b4b3ebcd6d3c127884ede8eb70cfbadcabe7e37a/pkg/chunk/schema.go#L853 is to find all index seriesIDs for specific metric name, label name and label value.

For example, if you have two series:
- metric{l1=“a”, l2=“b”}
- metric{l1=“a”, l2=“c”}

Then both will have (among other entries) also following entry (generated here: https://github.com/cortexproject/cortex/blob/b4b3ebcd6d3c127884ede8eb70cfbadcabe7e37a/pkg/chunk/schema.go#L791):
- HashValue=shard:bucketHashKey:metric:l1
- RangeValue=sha256(“a”)\0<seriesID>\0\0’8’\0
- Value=“a”

SeriesID will be different for these two series.

Query you have posted is used for PromQL expression like: `metric{l1=“a”}`, and it will return both index entries with seriesID for both series.

Without knowing much CQL, I think you’re correct in that using RangeValue here doesn’t add much, since WHERE condition also checks Value.

However, I don’t think check for RangeValue can be removed, because that would break when searching for Value=“-“ ... it would also return index entries for `seriesRangeKeyV1`.

**Comment by storyicon** [comment]
Thank you @pstibrany, if my understanding is correct, you should mean that RangeValue can be used to distinguish the type of index, like this:
https://github.com/cortexproject/cortex/blob/b4b3ebcd6d3c127884ede8eb70cfbadcabe7e37a/pkg/chunk/schema.go#L20-L34
Because I'm thinking about doing some specific query optimization, I wonder if there are other possible meanings for comparing ranges on RangeValue?

In addition, if you know, can you answer this issue by the way, this has really troubled me for a long time: https://github.com/cortexproject/cortex/issues/2665.
Thanks !
