### ISSUE TITLE
Enhancement Request: Retention Policies Defined by Tenant

### ISSUE THREAD

**Issue by Andrewpk** [cortexproject/cortex#2876]
Rather than having to spin up separate infrastructure to define a different retention policy via the schema config, it would be great if we could define schema configs/retention policies on a per tenant basis.

I imagine this could be accomplished in a few different ways such as allowing multiple schema configs to be defined with tenant ID's as a value on a `tenant` property, or even a new cortex configuration option that accepts an object of `tenant => retention_policy_duration`

**Comment by pracucci** [comment]
👋  Andrew and thanks for opening this issue.

I do agree we should have a per-tenant retention policy. It's something not trivial to achieve with the Cortex chunks storage because of the large number of object stored in the chunks store, while we expect it to be fairly easy to achieve in the blocks storage because of the relatively small number of objects.

**Comment by pracucci** [comment]
_Still valid. We wanna do it for the blocks storage._

**Comment by roidelapluie** [comment]
I would like this as well, with an extra thing:

It would be super nice to have the tenants specified as regexes. that way:

- all tenants that  ends with *dev can have lower retention policy.
- it also matches the cortex philosophy of not listing all tenants in config files.

**Comment by pracucci** [comment]
_Still valid, something we plan to do in the short/medium term in the blocks storage_

**Comment by jtlisi** [comment]
Can be closed now that #3879 has been merged
