### ISSUE TITLE
Easiest way to disable all rate/ingestion limits?

### ISSUE THREAD

**Issue by amckinley** [cortexproject/cortex#2924]
We use cortex internally with a single "customer" ID. I keep bumping up against various rate limits and changing the overrrides, but I'd like to just disable all the rate limiting entirely. Is there an easy way to accomplish that without playing whack-a-mole, one limit at a time? Can I just set every limit to `0` to disable them?

**Comment by pracucci** [comment]
I would suggest to look at all limits in the config https://cortexmetrics.io/docs/configuration/configuration-file/#limits_config and set them to 0 when the doc states that 0 means disabled, an high number otherwise. I will also double check the doc to ensure "0 to disable it" is correctly documented, because some limits may support it but not reflect it in the doc.
