### ISSUE TITLE
Ruler API returns 404 for existing route /api/prom/rules

### ISSUE THREAD

**Issue by robx** [cortexproject/cortex#2967]
The endpoint /api/prom/rules returns HTTP 404 Not Found when there are no rule groups: https://github.com/cortexproject/cortex/blob/106aa42093a6286852fcb5cddffb6e8b978c9d1e/pkg/ruler/api.go#L412.

It's good to get a 404 for /api/prom/rules/grp when rule group "grp" doesn't exist.  But /api/prom/rules does exist anyway, even if there's no group. 404 indicates that the resource at /api/prom/rules doesn't exist, not that it's an empty collection.

(Besides theoretical ideas of correctness, this makes the API hard to work with, because there's no easy way to determine if you got the right URL. If you get a 404, you'd have to check for the body text "no rule group founds".)

**Comment by gotjosh** [comment]
There's more to uncover here. Given this is a multitenant system, we should be verifying whenever the user has a manager running and return 404 (or not) based on that -- which is the thing that signals "I have a user in this system". For the no rules on all endpoints it feels like it should be a 204. 

Now, with that in place, you would still receive a 404 in the case where a user has no rules (because the manager only starts for a user when there are rules) so I don't think this would be fixable by Cortex.

**Comment by robx** [comment]
I see, that makes sense. Closing this then, thanks for the explanation!

**Comment by gotjosh** [comment]
Let's leave it open because we'd still need to do the check against the manager running. cc: @pracucci

**Comment by gotjosh** [comment]
still valid

**Comment by pracucci** [comment]
_Reopening it because still valid_

**Comment by pracucci** [comment]
_Still valid_
