### ISSUE TITLE
S3 endpoint in single-process-config-blocks.yaml needs to be updated

### ISSUE THREAD

**Issue by vikram-yerneni** [cortexproject/cortex#3150]
Looks like the [https://github.com/cortexproject/cortex/blob/master/docs/configuration/single-process-config-blocks.yaml#L63](url) is still using the old S3 endpoint configuration (endpoint: s3.dualstack.us-east-1.amazonaws.com). It looks like AWS endpoint for the s3 bucket needs to be "s3.amazonaws.com".

**Comment by pstibrany** [comment]
Hi Vikram, do you have any authoritative source about this? From my reading of https://docs.aws.amazon.com/AmazonS3/latest/dev/dual-stack-endpoints.html, `s3.dualstack.us-east-1.amazonaws.com` should be fine.

**Comment by vikram-yerneni** [comment]
Hi Peter,
When I tested the single instance setup and ran with it, I hit a roadblock "301 response missing Location header" and found the endpoint I am using is not correct. I provided the bucket name I created in our Dev Env and used the default endpoint "s3.amazonaws.com" and the configuration took it in. I guess AWS documentation might needs an update out something.
Thanks
Vikram Y

**Comment by pracucci** [comment]
@vikram-yerneni Could you provide a config (redacted of sensitive data) to reproduce it? The problem is not changing a line in the default config, but to me the current config (which is regional) is more correct than `s3.amazonaws.com` (which to my knowledge is the old endpoint for `us-east-1`). Also `s3.amazonaws.com` is IPv4 only.

For example, if I run `curl -v https://s3.dualstack.us-east-1.amazonaws.com/test` I don't get any redirect (but a 403 response as expected).
