### ISSUE TITLE
API endpoints for making atomic changes across multiple rule groups or namespaces

### ISSUE THREAD

**Issue by domasx2** [cortexproject/cortex#3249]
**Is your feature request related to a problem? Please describe.**
Working on rule editing in Alerting UI plugin for Grafana. Some of the edit operations currently require multiple API calls to cortex to persist. In case one of the calls fails, it might leave rules config in an undesired state. It would be nice to be able to persist these changes using a single endpoint and ensure atomicity.

The problematic operations are:
* move rule between groups 
    - currently requires 2x `Set rule group` calls
* move group between namespaces
    - currently requires `Delete rule group` and `Set rule group` calls
* rename group
    - currently requires `Delete rule group` and `Set rule group` calls
* rename namespace
   - currently requires `Delete namespace` and multiple `Set rule group` calls

**Describe the solution you'd like**
What do you think about having endpoints to update an entire namespace and/or entire rules config in one call? Is that plausible? Any other ideas?

Thanks!

**Comment by gotjosh** [comment]
In case of updating a whole namespace, I think the main problem here is that no matter how we look at it, it can't really be atomic due to our storage model - where we store one rule group per file.

There are some things we can do to help alleviate some of this pain, I think:


> move rule between groups

There's not much we can do here, it would require the same amount of operations from our side.


> move group between namespaces

Similar to the above.
 
> rename group

We can probably implement this as an independent operation with `PUT|PATCH /api/v1/rules/{namespace}/{groupName}`

> rename namespace

We could probably reduce the number of calls by allowing support to update multiple rule groups with `POST /api/v1/rules/{namespace}`


@pstibrany @pracucci @bboreham WDYT?

**Comment by pracucci** [comment]
I agree with @gotjosh that, even if we introduce an "uber API" to do everything in a single call, under the hood we wouldn't be able to guarantee atomicity anyway (when using the object storage). We could rollback all changes on failures (which is not guaranteed atomicity), but it's not much different than a rollback done by the client side.

How frequent is this problem?

**Comment by domasx2** [comment]
So in our plugin's case the client is a user's browser. I'm somehwat hesitant to rely on request followup / rollbacks in code running on a user's browser. Doing everything on cortex side would still likely be more reliable, as well as having the advantage of being able to validate all inputs using the same validation logic before applying the operations.

That said, we haven't released these rule editing features yet, so not sure if this is going to be an issue at all. Perhaps we can go with a naive approach using current endpoints and see how it works out :)

**Comment by domasx2** [comment]
Alright, closing this, thanks guys. Will try optimistic approach first and see if there's really gonna be a problem.
