### ISSUE TITLE
Support manual failovers for HA tracker

### ISSUE THREAD

**Issue by jpdstan** [cortexproject/cortex#3462]
**Is your feature request related to a problem? Please describe.**
We recently ran into a situation where the leader replica of a shard within our HA ring was failing to scrape a subset of its targets. We saw the follower replica of that same shard were scraping those targets just fine, but realized we had no way of forcefully electing the follower replica to takeover writes for that shard, and was left with no other choice but to churn the leader to do so. 

**Describe the solution you'd like**
Not sure how this would manifest but the most transparent solution that comes to mind is having a "Failover" button or something of that sort in this dashboard:

![image](https://user-images.githubusercontent.com/5893781/98155532-3eedee80-1e8b-11eb-82e6-a79dbbf6312d.png)

**Describe alternatives you've considered**
Having a way to manually failover rather than forcefully churning servers sounds reasonable.

**Additional context**
First raised in [CNCF #cortex slack](https://cloud-native.slack.com/archives/CCYDASBLP/p1604453714274600)

**Comment by pracucci** [comment]
I agree this would be useful. I found myself in the same situation as well.

At the current stage, we don't keep track of the non-elected replica names, so I'm wondering how the "Failover" button could work. We could just remove the current elected replica from the key-value store, but the same replica could be elected again, and there's no guarantee the "other" replica could be elected".

Alternatively, we could keep track of all other "replicas" in the distributor memory, so that we can show them in the table and the failover could pick one of them (if any). However, we need to be carefully and make sure we don't end up in situations where there's a split brain (two replicas elected, as seen by different ingesters).

More thoughts are required and I'm open to ideas on the topic. Thanks!

**Comment by pracucci** [comment]
_Still valid_
