### ISSUE TITLE
QUESTION: Why does Cortex create so many On-Demand dynamoDB tables

### ISSUE THREAD

**Issue by tomjohnburton** [cortexproject/cortex#3487]
I'm using chunks storage. I have one table for both index and chunks running in provisioned mode. The other 70 are all on on demand. What settings control this?

**Comment by pracucci** [comment]
The table-manager, running as part of the Cortex chunks storage, is expected to create 1 table for index and 1 table for chunks (if configured to be stored in a key-value store too) for each "period". Please take a look at [this doc](https://cortexmetrics.io/docs/chunks-storage/table-manager/) to learn more about what a "period" is and how to configure it.

Just as an hint, I would suggest:
- Make sure the configured period is relatively large (eg. 7 days)
- Make sure the [1st schema `from`](https://cortexmetrics.io/docs/chunks-storage/schema-configuration/) is not older than the beginning of the 1st period you started using Cortex. Table-manager will create a table for each period since then.

**Comment by tomjohnburton** [comment]
Great thanks for your clear explanation!
