### ISSUE TITLE
ruler ListRules return error when empty groups return 

### ISSUE THREAD

**Issue by AllenzhLi** [cortexproject/cortex#3496]
https://github.com/cortexproject/cortex/blob/d1cdc1693cf2666cc79e2a3e292d2d0163807df0/pkg/ruler/api.go#L398-L402

I think empty groups is different from error, if recv empty, then should return empty.

**Comment by pracucci** [comment]
This API is both called with and without namespace:
- /api/v1/rules
- /api/v1/rules/{namespace}

When it's called with namespace, I would say returning 404 is OK if there are no rules (because I think there's no way to distinguish whether the namespace exists or not, so we could assume a non existing namespace has been queried).

However, when it's called without namespace, I'm wondering whether we should return a 200 with empty rule groups or continuing returning 404.

@gotjosh what's your take?

**Comment by AllenzhLi** [comment]
When request to a error url, also get 404, maybe need clearer information

**Comment by gotjosh** [comment]
Hi @AllenzhLi ,

Thank you for the issue! Under our current semantics, we have no use-case for a 0 rule group. You can't even create them:

https://github.com/cortexproject/cortex/blob/cf6f899dd1a1788875ff0d55e7191c6b05b89e55/pkg/ruler/manager.go#L265-L268

This is intentional given Cortex multi-tenants nature.

**Comment by gotjosh** [comment]
> However, when it's called without namespace, I'm wondering whether we should return a 200 with empty rule groups or continuing returning 404.

IMO the current behaviour seems correct.

**Comment by AllenzhLi** [comment]
> Hi @AllenzhLi ,
> 
> Thank you for the issue! Under our current semantics, we have no use-case for a 0 rule group. You can't even create them:
> 
> https://github.com/cortexproject/cortex/blob/cf6f899dd1a1788875ff0d55e7191c6b05b89e55/pkg/ruler/manager.go#L265-L268
> 
> This is intentional given Cortex multi-tenants nature. Do you have a use-case for creating 0 rules rule groups that we're missing?

I write a script list all rules which in cortex to do some check, when no rules in cortex, it return 404 which is confused.
