### ISSUE TITLE
ruler api some return json and others return yaml

### ISSUE THREAD

**Issue by AllenzhLi** [cortexproject/cortex#3502]
https://github.com/cortexproject/cortex/blob/bdcbb0397f174b9001dc906ad1b69c2e39874ab7/pkg/api/api.go#L233-L254

When I access above api in my chrome，the returned data format is inconsistent

/api/v1/rules     yaml
/api/v1/alerts    yaml
![image](https://user-images.githubusercontent.com/16623135/99492095-eac52d00-29a7-11eb-8eea-0e6999906722.png)

/api/prom/api/v1/rules    json
/api/prom/api/v1/alerts   json
![image](https://user-images.githubusercontent.com/16623135/99492178-0d574600-29a8-11eb-81b9-c6933f5f681a.png)

**Comment by AllenzhLi** [comment]
ListRules call func marshalAndSend  to return

https://github.com/cortexproject/cortex/blob/bdcbb0397f174b9001dc906ad1b69c2e39874ab7/pkg/ruler/api.go#L289-L302

I am confused!

**Comment by gotjosh** [comment]
Hi again @AllenzhLi ! 

This is intentional. The first endpoint is the configuration API, the second is the Prometheus compatible endpoint. We use YAML for the configuration and must do whatever Prometheus does for the compatible one - hence the return of JSON. 

This is all detailed as part of the API documentation: https://cortexmetrics.io/docs/api/#list-rules

Is there something we're missing?

**Comment by AllenzhLi** [comment]
Thanks, I understand.
