### ISSUE TITLE
"Ring status" for distributors

### ISSUE THREAD

**Issue by Andrewpk** [cortexproject/cortex#3656]
**Is your feature request related to a problem? Please describe.**
It's very easy to see ingester and ha ring status, but distributor ring status is only _sort of_ viewable via Consul

**Describe the solution you'd like**
A status page that shows the distributor ring status similar to how we can currently view ingester ring status.

**Describe alternatives you've considered**
Currently I take a look at the distributor key in consul.

**Additional context**
It would just help with troubleshooting if distributors are having trouble creating/joining.

**Comment by pracucci** [comment]
Good point!

I did introduce the distributors ring. The reason why I didn't binded the HTTP UI at that time was because the distributors currently use only the `ring.Lifecycler` while the UI requires `ring.ReadRing` (this would also watch for the ring key changes).

**Comment by ethervoid** [comment]
Can I take this one? :)

**Comment by pracucci** [comment]
> Can I take this one? :)

Sure. What's your plan here?

**Comment by ethervoid** [comment]
Well by now I need to check how everything works because, to be honest, I don't have a clear idea yet on how the ring and distributors work so it'll take some time but I think is a good issue to keep learning about the internals.

**Comment by ethervoid** [comment]
Hi! I want to leave a comment here to say I'm still working on this issue :). It's taking me a while to get up to speed with all the nitty-gritty of the ring code

**Comment by ethervoid** [comment]
@pracucci I've been taking a look at this issue for some time and trying to understand how the ring and LifeCyclers works and here are the first approach and/or questions to this issue:

I'm still trying to fully understand what is the difference between the ReadRing and the LifeCycler but I can see that the [LifeCycler](https://github.com/cortexproject/cortex/blob/master/pkg/ring/lifecycler.go#L148) is creating its own store and providing some access methods to the data inside while the [BasicLifeCycler](https://github.com/cortexproject/cortex/blob/master/pkg/ring/basic_lifecycler.go#L84) is relying on the passed store. 

Also, I've seen that the ReadRing/BasicLifeCycler, like the one used by the ruler, is implementing some delegating policies and the distributor currently doesn't need those.

My first approach was to mimic what rules does and create reading and BasicLifeCycler for the distributor in order to be able to call the [HTTP handler from the ring](https://github.com/cortexproject/cortex/blob/master/pkg/ring/http.go) but I was implementing things like the [lifecycler delegates](https://github.com/cortexproject/cortex/blob/master/pkg/ring/basic_lifecycler.go#L20-L38) that I think I shouldn't be implementing so I discarded that one.

My next approach would be to mimic the [ring HTTP handler](https://github.com/cortexproject/cortex/blob/master/pkg/ring/http.go) and have that one show a status page for those who only use the lifecycler like the distributor.

What do you think?

PD: I've been trying to create a ring of multiple distributors in my local env. but I wasn't able to have more than one ingester instance in memberlist/consul. Do I have to include anything else that `-distributor.ingestion-rate-limit-strategy=global`?

**Comment by pracucci** [comment]
The `Lifecycler`  and `BasicLifecycler` are designed to register, unregister and heartbeat a single instance within the ring (the instance itself). Because of this, they don't keep the whole ring data structure in-memory so, unless changing it, you don't have to information required to build the ring status page.

That being said, I believe the easiest solution would be just using the `ring.Ring` client (which is a read-only client over the ring) in the distributor too, so you can use its HTTP handler.

**Comment by ethervoid** [comment]
Thank you very much for your answer!

> That being said, I believe the easiest solution would be just using the ring.Ring client (which is a read-only client over the ring) in the distributor too, so you can use its HTTP handler.

You mean to have at the same time the LifeCycler and the `ring.Ring` or just the `ring.Ring` in the distributor logic. I'm asking this because for example the ruler [uses both of them](https://github.com/cortexproject/cortex/blob/master/pkg/ruler/ruler.go#L222-L223)

**Comment by pracucci** [comment]
> You mean to have at the same time the LifeCycler and the ring.Ring or just the ring.Ring in the distributor logic

The distributor needs the `Lifecycler` because distributors form a ring themselves when global limits are enabled. So my suggestion is to add `ring.Ring`  on top of that, just for the web UI purposes.

**Comment by ethervoid** [comment]
Understood, thank you @pracucci :)
