### ISSUE TITLE
S3 "Access Denied" failures not getting tracked as blockLoadFailures

### ISSUE THREAD

**Issue by amckinley** [cortexproject/cortex#3757]
**Describe the bug**
We're using S3 with blocks mode as the backing store for our cortex cluster. We've observed that when our `store-gateways` occasionally have problems reaching S3 (because of IAM issues on our side), we see the following errors in the `store-gateway` logs:

```
level=warn ts=2021-01-28T23:27:20.952662934Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=246.329032ms err="rpc error: code = Aborted desc = fetch series for block 01EWQ7HNC7X3PK86CMA5XDSY3R: expanded matching posting: get postings: read postings range: get range reader: Access Denied" msg="gRPC\n"
level=warn ts=2021-01-28T23:27:20.969744145Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=111.836424ms err="rpc error: code = Aborted desc = fetch series for block 01EX38275A5GZA00F5E3WA0J70: expanded matching posting: get postings: read postings range: get range reader: Access Denied" msg="gRPC\n"
level=warn ts=2021-01-28T23:27:20.969782314Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=58.609217ms err="rpc error: code = Aborted desc = fetch series for block 01EWPSVCZHFVESR9XF85R8NHM1: expanded matching posting: get postings: read postings range: get range reader: Access Denied" msg="gRPC\n"
level=warn ts=2021-01-28T23:27:20.979500074Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=145.718184ms err="rpc error: code = Aborted desc = fetch series for block 01EWME9YRPVVSWRHBWE9MCH79Q: expanded matching posting: get postings: read postings range: get range reader: Access Denied" msg="gRPC\n"
level=warn ts=2021-01-28T23:27:20.980301479Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=62.485117ms err="rpc error: code = Aborted desc = fetch series for block 01EWN9SHM0AN6R9452BWMRAQEX: expanded matching posting: get postings: read postings range: get range reader: Access Denied" msg="gRPC\n"
```

This has downstream effects where our queriers (and users) get errors like this:
![image](https://user-images.githubusercontent.com/54160/106218927-386eca80-618d-11eb-9006-e02bb238ebcd.png)

The issue is that there seems to be a bug where those^^ exceptions aren't getting counted as `blockLoadFailures`, which makes it hard to track and alert on these errors. If these errors are actually getting counted under some other internal cortex metric, please let us know what it is so we can close this out :)

**To Reproduce**
1. Start Cortex v1.5.0 with S3 configured as the blocks storage
2. Modify the permissions on the target S3 bucket to prevent the `store-gateway` from accessing it (this is a guess at a repro, but I expect it would work fine)

**Expected behavior**
We expect this metric to get incremented so we can alert on it: https://github.com/cortexproject/cortex/blob/master/pkg/storegateway/bucket_store_metrics.go#L16

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: `cortex-jsonnet`

**Storage Engine**
- [X] Blocks
- [ ] Chunks

**Additional Context**
jsonnet config and k8s manifests available on request

**Comment by pracucci** [comment]
👋  @amckinley Let me try to share some thoughts.

The metric `cortex_bucket_store_block_load_failures_total` (which you're referring to) counts the number of failures when loading a block's index-header in the store-gateway. This is an operation which happens only once per block per store-gateway when a new block is discovered by the store-gateway. What basically happens is: an ingester or compactor uploads a new block, the store-gateway discovers it, it loads the block's metadata and index-header. If this operation fails, a +1 is done on that metric. This metric doesn't affect failures at query time.

> `level=warn ts=2021-01-28T23:27:20.952662934Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=246.329032ms err="rpc error: code = Aborted desc = fetch series for block 01EWQ7HNC7X3PK86CMA5XDSY3R: expanded matching posting: get postings: read postings range: get range reader: Access Denied" msg="gRPC\n"`

As you pointed out, the failing "read postings range" can happen at query time if the store-gateway is unable to read from the object store (for whatever reason, an "Access Denied" in your case). This is tracked by the low level metric `thanos_objstore_bucket_operation_failures_total`, which tracks any failure when accessing the object store. This metric has also an `operation` label, so in your case you could filter by `thanos_objstore_bucket_operation_failures_total{operation=~"get|get_range"}`.

Now, sporadic failures tracked by `thanos_objstore_bucket_operation_failures_total` don't necessarily lead to a failing query, because the querier may retry fetching data from store-gateway on failure, even if an elevated error rate needs to be investigate.

My suggestion would be to monitor `thanos_objstore_bucket_operation_failures_total` (we do in our [OSS dashboards](https://github.com/grafana/cortex-jsonnet/blob/master/cortex-mixin/dashboards/reads.libsonnet)) but not necessarily alert on it. I would actually alert on query failures, as tracked by the query-frontend. For example:

```
sum(rate(cortex_request_duration_seconds_count{container="query-frontend",route=~"(prometheus|api_prom)_api_v1_.+",status_code=~"5.*"}[1m]))
/
sum(rate(cortex_request_duration_seconds_count{container="query-frontend",route=~"(prometheus|api_prom)_api_v1_.+"}[1m]))
```

**Comment by amckinley** [comment]
Thanks the explanation @pracucci! We'll set up an alert on `cortex_bucket_store_block_load_failures_total` to help us track down the issues on our end. And we already have that `cortex_request_duration_seconds_count` alert setup :)
