### ISSUE TITLE
Support the TSDB stats API

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#4059]
Currently to understand the cardinality of their metrics and which metrics are contributing how much overhead, we need to resort to scripts that run PromQL for each metric name. See: https://grafana.com/docs/grafana-cloud/billing-and-usage/prometheus/usage-analysis-explore/

But there is now an upstream API that returns this info in a single API call and is much more efficient as it reads the index directly without touching promql. https://prometheus.io/docs/prometheus/latest/querying/api/#tsdb-stats

We should support it in Cortex directly.

**Comment by weeco** [comment]
What exactly do you mean by "support it"?

Do you intend to show each prometheus instance's TSDB stats in the frontend somewhere so that you as an Administrator can assist users in spotting these metrics?

How can you access the Prometheus servers that usually just push metrics into Cortex? Many of these are most likely not accessible from the "remote Cortex cluster" or am I missing something?

**Comment by 56quarters** [comment]
> Do you intend to show each prometheus instance's TSDB stats in the frontend somewhere so that you as an Administrator can assist users in spotting these metrics?

@weeco My interpretation is that this would add an API to expose stats about the head blocks of the TSDB each ingester are writing, not the stats of the prom instances writing to Cortex.

**Comment by bboreham** [comment]
I had the same idea, only I expressed it as "Cortex should have the prometheus TSDB status page, aggregated per-tenant"

This would be implemented quite like `Distributor.UserStats()`, calling across all ingesters and adding up the results.

Example of Prometheus status page:

![image](https://user-images.githubusercontent.com/8125524/121726461-7fc57a00-cae2-11eb-92be-f3cb73805420.png)

**Comment by 56quarters** [comment]
still valid
