### ISSUE TITLE
Memberlist: ReportWriteToErrors is not currently exposed

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#4060]
The `ReportWriteToErrors` config in the memberlist `TCPTransportConfig` is not currently exposed to the user and there is not way to configure it.

This may be intentional and exist only for testing. However, if that is the case, I recommend we remove it.

**relevant code:**

- [ReportWriteToErrors field](https://github.com/cortexproject/cortex/blob/f2194ff4290aac5147339ce8eccab6d1e70eedc6/pkg/ring/kv/memberlist/tcp_transport.go#L49-L51)
- [ReportWriteToErrors usage](https://github.com/cortexproject/cortex/blob/f2194ff4290aac5147339ce8eccab6d1e70eedc6/pkg/ring/kv/memberlist/tcp_transport.go#L386-L388)

**Comment by pstibrany** [comment]
Reason for not exposing this is that when you actually enable it, memberlist will not like it very much... I don't remember what exactly happened, but remember that it didn't do anything useful, and was counter-productive. That's why it's not exposed.

We can try to enable it and see what happens again, or just remove it completely (but never return errors from `WriteTo` method).

**Comment by pracucci** [comment]
> We can try to enable it and see what happens again, or just remove it completely (but never return errors from WriteTo method).

I think leaving it in the code, but not allowing to configure it, may be deceiving. I'm OK to remote it completely if dangerous. We can re-introduce it anytime, if needed.
