### ISSUE TITLE
More memory consumption with large number of users with fewer metrics

### ISSUE THREAD

**Issue by sriramachelankuri** [cortexproject/cortex#4194]
**Describe the bug**
Cortex is consuming a lot of memory when we have more users for say 4500 and the total number of time series is close to around a 2.5Million. 

**To Reproduce**
Create a cluster with 9 nodes and 9 replicas ( ingester, storage gateway, compactor, distributor, query-frontend, querier) rest all one replicas.
Each node is having 16 CPU 64 GB of RAM. 
And wring around 15K samples/sec across all the clients. 

**Expected behavior**
It suppose to be working without any issues as the number of the time series are below 3 million.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, GCP] have 

**Storage Engine**
- Blocks

**Additional Context**
Ingester and storage gateways are getting failed after 1 hr run.

**Comment by pstibrany** [comment]
Hello. With large number of tenants it is recommended to enable shuffle sharding on write path, to distribute tenants between ingesters. With no shuffle sharding, every tenant will end up on every ingester.

Each tenant in the ingester requires open TSDB for that tenant, and this in turns requires extra memory. You can tune this memory by using `-blocks-storage.tsdb.stripe-size` and `-blocks-storage.tsdb.head-chunks-write-buffer-size-bytes` flags. Default values are somewhat high -- we use stripe-size=32 and head-chunks-write-buffer-size-bytes=131072 on our cluster with lot of small tenants. You can also reduce `-blocks-storage.tsdb.wal-segment-size-bytes=16777216` (our value, default is 128MiB). Note that all these values are per TSDB (ie. tenant in ingester).

Store gateways will need to deal with a lot of blocks. To reduce the amount of blocks, it may be advisable to compact blocks to higher time ranges. Default max in Cortex is 1 day, but you can go to eg. 7 days -- this alone will give you 7 times fewer blocks. This may be acceptable if blocks are small (with 3M series across 4500 tenants, they likely are). Shuffle sharding blocks across store-gateways is not as critical as for ingesters.

With so many tenants, it's good to use many compactors, so that they can keep up with influx of blocks.

**Comment by sriramachelankuri** [comment]
Thanks, Peter I have enabled shuffle sharding on the write path. Will try to reduce the stripe size and other parameters as well. Would like to know I have a mix of customers in the environment where 70% of the tenants are very small and 30% of the tenants are big. Will, there be any impact on performance in terms of write speed and read response time by reducing the configurations you have suggested?

**Comment by sriramachelankuri** [comment]
Ingesters are getting failed and not able to start with the following error after running successfully with more than 8hrs

level=error ts=2021-05-25T16:02:00.855803922Z caller=ingester_v2.go:1600 msg="unable to open TSDB" err="failed to open TSDB: /data/cortex-tsdb-ingester/1103465: reloadBlocks: 2 errors: corrupted block 01F6HCKAHZ492DC71S9QVFT4EF: mmap, size 1854: cannot allocate memory; corrupted block 01F6HJ53MD1SEE04N9KPEP1T2S: mmap, size 2589: cannot allocate memory" user=1103465
level=error ts=2021-05-25T16:02:00.90447873Z caller=ingester_v2.go:1600 msg="unable to open TSDB" err="failed to open TSDB: /data/cortex-tsdb-ingester/1103467: reloadBlocks: 2 errors: corrupted block 01F6HCJPBV2JYSR2WAH9G9BP92: mmap files: mmap, size 596: cannot allocate memory; corrupted block 01F6HJ53N8E93MTJRT4WCWHDB7: mmap files: mmap, size 36432: cannot allocate memory" user=1103467

**Comment by pracucci** [comment]
> `level=error ts=2021-05-25T16:58:24.710966782Z caller=ingester_v2.go:1600 msg="unable to open TSDB" err="failed to open TSDB: /data/cortex-tsdb-ingester/1103879: mmap files, file: /data/cortex-tsdb-ingester/1103879/chunks_head/000010: mmap, size 11072: cannot allocate memory" user=1103879`

Make sure you haven't hit the node memory limit or the memory map areas limit (see [this playbook](https://github.com/grafana/cortex-jsonnet/blob/main/cortex-mixin/docs/playbooks.md#cortexmemorymapareastoohigh) to learn more about it).
