### ISSUE TITLE
Question regarding OpenStack Swift integration

### ISSUE THREAD

**Issue by dextras** [cortexproject/cortex#4321]
I am planning to use Cortex as long time storage for timeseries data. Originally I was planning to use Chunks Storage because it had Apache Cassandra as a possible integration (in my solution I cannot use a cloud provider such as Amazon/Google/Microsoft). 

Now that Chunks Storage is deprecated I am pondering to switch to Block Storage and use OpenStack Swift as a storage. However I am worried that, in documentation OpenStack Swift integration is labeled as experimental. Therefore I have few questions.

1. Are there plans to add other open source integrations to block storage (such as Cassandra)
2. What does 'experimental' mean in the contex of OpenStack Swift, are there any problems with this integration?
3. Are there plans to move this (OpenStack Swift) integration from experimental to "production" just like other integrations?

I would be grateful for some guidance.

**Comment by pracucci** [comment]
> Are there plans to add other open source integrations to block storage (such as Cassandra)

Not for now.

> What does 'experimental' mean in the contex of OpenStack Swift, are there any problems with this integration?

We're not aware of issues. Typically experimental means it hasn't been battle tested by any maintainer or active Cortex users which reported back positive feedback (happy to hear your feedback!).

> Are there plans to move this (OpenStack Swift) integration from experimental to "production" just like other integrations?

Yes, definitely. I guess we just need a bit more production feedback on it.

**Comment by dextras** [comment]
@pracucci thanks a lot for your answer. I will proceed with OpenStack Swift and will come back to you with my feedback after the solution is implemented and verified by us.

**Comment by ubcharron** [comment]
I can offer some feedback on Swift.

We've been running Cortex on OpenStack Swift in production since February 2021 (so about 6 months ago). Overall, the experience has been very smooth.

The only problem we've had was caused by a bad Swift node which would sometimes timeout during an upload. The failure wasn't handled properly in Thanos and this lead to some data loss (https://github.com/cortexproject/cortex/issues/4055).  The fix is in https://github.com/thanos-io/thanos/pull/4218. It didn't make it in Cortex v1.10.0, but the Thanos tree was updated recently, so it should be included in the next Cortex release (v1.11.0?). (I'd suggest manually patching in the meantime.)
