### ISSUE TITLE
Failed TestStoreGateway_BlocksSyncWithDefaultSharding_RingTopologyChangedAfterScaleUp

### ISSUE THREAD

**Issue by pracucci** [cortexproject/cortex#4546]
I've just seen this test failing ([CI](https://github.com/cortexproject/cortex/runs/4091281875?check_suite_focus=true)). We should investigate it:
```
--- FAIL: TestStoreGateway_BlocksSyncWithDefaultSharding_RingTopologyChangedAfterScaleUp (17.94s)
    gateway_test.go:406: random generator seed: 1635936443186330968
    gateway_test.go:496: expected 40, got 16
FAIL
```

**Comment by bboreham** [comment]
Another one https://github.com/cortexproject/cortex/runs/4103618650
```
--- FAIL: TestStoreGateway_BlocksSyncWithDefaultSharding_RingTopologyChangedAfterScaleUp (18.75s)
    gateway_test.go:406: random generator seed: 1636021349283089808
    gateway_test.go:496: expected 40, got 16
FAIL
```

**Comment by pedro-stanaka** [comment]
Had the same running on my local:

```
?       github.com/cortexproject/cortex/pkg/storage/tsdb/testutil       [no test files]
--- FAIL: TestStoreGateway_BlocksSyncWithDefaultSharding_RingTopologyChangedAfterScaleUp (10.34s)
    gateway_test.go:406: random generator seed: 1638348556975475935
    gateway_test.go:496: expected 40, got 0
FAIL
FAIL    github.com/cortexproject/cortex/pkg/storegateway        170.002s
```

**Comment by bboreham** [comment]
I believe this is caused by the issue identified in https://github.com/grafana/dskit/issues/108 - the test is polling for metrics to update, but they won't update until the 10-second timer. Since it only waits 5 seconds this may not work.
https://github.com/cortexproject/cortex/blob/dd698bc411254e3d31b92b2e267634d735dcfb89/pkg/storegateway/gateway_test.go#L496
So when we update dskit with the change in https://github.com/grafana/dskit/pull/107 it should be ok.
Update is proposed in #4601.
