### ISSUE TITLE
How to enable (wrapped) Prometheus debug logging?

### ISSUE THREAD

**Issue by paul-bormans** [cortexproject/cortex#4925]
I have enabled debug logging through the Cortex configuration but the wrapped Prometheus logging (for instance from the ruler isn't visible in the output); how do i enable it?

The /config endpoint returns:

```
server:
  log_level: debug
```
Also an extra arg is provided to all Cortex components (pods):
`-log.level=debug`

For instance in the Ruler i expected to see an INFO logging statement:
`      Starting rule manager...`
See https://github.com/cortexproject/cortex/blob/master/vendor/github.com/prometheus/prometheus/rules/manager.go#L943)

But it's not in the output while logging (even debug) from the wrapper (Cortex) code is present:

```
level=info ts=2022-10-20T08:33:46.785816391Z caller=ruler.go:452 msg="ruler up and running"
level=debug ts=2022-10-20T08:33:46.785903138Z caller=ruler.go:490 msg="syncing rules" reason=initial
<...>
ts=2022-10-20T08:35:17.680398843Z caller=spanlogger.go:87 org_id=system method=blocksStoreQuerier.selectSorted level=debug msg="no blocks found"
```

Running Cortex version: v1.13.1 on K8S

**Comment by alanprot** [comment]
This is because this log was not present on the v1.13.1 as we can see below:

https://github.com/cortexproject/cortex/blob/de2ef5e836206ca9796945029b6b6f097fd11b26/vendor/github.com/prometheus/prometheus/rules/manager.go#L935-L939

This log line was added on the following prometheus update that is currently only in master:

https://github.com/cortexproject/cortex/commit/575645b2faa0fe15b92aa320b4199cd49c5b3701

**Comment by friedrichg** [comment]
answered
