### ISSUE TITLE
Report the use of components with vulnerabilities in cortex

### ISSUE THREAD

**Issue by HouqiyuA** [cortexproject/cortex#5934]
Dear Team Members:
Greetings! Our team is very interested in your project. we performed source code perspective security analysis (SCA) and vulnerability library association analysis on this project and found that components with vulnerabilities are still being used into this project.We would like to report this issue to you,so that you can fix and improve it accordingly. I add the details in json file below. Please confirm whether this problem really exists and confirm with us. Looking forward to hearing from you and discussing more details with us, thank you very much for your time and attention.

Note: Each "affect_components" field in the report represents the vulnerable component introduced by this project. The other is the vulnerability information associated with it.

Qiyu Hou

[cortex-master_report.json](https://github.com/cortexproject/cortex/files/15246155/cortex-master_report.json)

**Comment by friedrichg** [comment]
Do not appreciate security reports on github.
Per https://github.com/cortexproject/cortex?tab=security-ov-file#readme you should report this information per email.

But since you made this public, I address it publicly. As you correctly point out in your json. This consul api bug was fixed in the version 1.11.5, We currently are in 1.27.0. That means we are not affected.
