### ISSUE TITLE
Please add Release tags

### ISSUE THREAD

**Issue by fmunteanu** [cortexproject/cortex#768]
With Releases, you can provide links to binary files, as well release notes describing your changes. Please add one, to facilitate rpm packaging as well.

**Comment by bboreham** [comment]
Hi @fmunteanu , welcome to the Cortex community.

Can you say a bit more about why binary files and rpm packaging are important to you?

A release tag has other implications: it says that this commit is better than the ones that follow.  Cortex does not have that style of development at the moment: we make changes rapidly and if things go wrong we fix them.

**Comment by fmunteanu** [comment]
Hi @bboreham from my perspective, I could package your product and deploy it to a closed environment with `yum install cortex-1.0.0`.

**Comment by rpofuk** [comment]
Are there docker containers ready on docker hub so I can deploy them?
Some tagging would for sure give more insights about project progress even if they don't mean stability... 

If you would just do tags 0.1, 0.2. and produce docker containers on hub accordingly that would for sure increase adoption because I could spin service up in seconds to play around.

**Comment by bboreham** [comment]
On every push to master, CI pushes images to quay.io, tagged `master-gitsha`.

**Comment by bboreham** [comment]
[Release 0.1.0](https://github.com/cortexproject/cortex/releases/tag/v0.1.0) now out
