### ISSUE TITLE
Do billing via a query

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#814]
We have a "billing" module in the Distributor, which talks to some other component which logs operations into a database.  It's counting number of calls and number of samples.

We have all this data in metrics from the uploading Prometheus, and if we didn't trust that then we could generate server-side metrics.  Then query those metrics once per hour or per day to populate the billing database.

This would be far more efficient because it's not doing an off-box call N times per second.

**Comment by juliusv** [comment]
Note that for upstream Prometheus we specifically say "do not use it for billing purposes": https://prometheus.io/docs/introduction/overview/#when-does-it-not-fit

Now Cortex has different tradeoffs, but with metrics-based billing, at least be aware that you can never become 100% accurate, because if you don't ship off state to be persisted immediately, you can always lose counter increments due to things like process restarts. At least that will estimate in the customer's favor. Maybe it's good enough.

**Comment by bboreham** [comment]
Fair point.  It seems reasonable to me to bill customers using a mechanism that is as reliable than the one we use to store their data.

If we wanted to bill per request we would need code in the Querier too.

**Comment by gouthamve** [comment]
We've added all the metrics to bill based on metrics (tenant IDs appear in labels).
