### ISSUE TITLE
Querier error returned as compressed binary data

### ISSUE THREAD

**Issue by leth** [cortexproject/cortex#938]
If I run a certain query in graph mode, I am told: `Error: rpc error: code = Code(413) desc = exceeded maximum number of samples in a query (100000)`
If I run the same query in table mode, instead I am told: ` Server error (rpc error: code = Code(500) desc = ��������4�M �0���V-���*ЕW�1��B��{ ��wg3�<Śo�� U�����^)N�ܨٯ�-N�|�!�H̸���<�FDZ�n���H~[RO�=ݨ(w�Ou�a��xt�a:~�����������+W����� ) `

**Comment by leth** [comment]
This issue started after 6024681c. @tomwilkie Perhaps this was introduced in #910 as it was the next build to release a new querier image?

**Comment by leth** [comment]
I'm not sure what fixed this, but it seems to no longer happen on the latest releases!

**Comment by leth** [comment]
Turns out we didn't test what we thought we had tested!

**Comment by bboreham** [comment]
It's working on `6024681c` and broken on `57b71bbf`, which is the first commit that produced a Querier image after the working one.

`57b71bbf` is from #910 which changed `httpgrpc.pb.go`.

**Comment by bboreham** [comment]
@leth gave me a tip which revealed what the corruption is - the code generating the error message is writing to a `compressedResponseWriter`, while `ErrorFromHTTPResponse` which pulls it out into gRPC is assuming it can use those bytes directly.

@tomwilkie does that raise any thoughts as to how we should avoid this?

**Comment by tomwilkie** [comment]
Can I look tomorrow? In Amsterdam for monitorama....

**Comment by bboreham** [comment]
So this was actually caused by #898 not #910, and the reason I was looking at the wrong commit is that a unit test failed on the merge for #910 https://circleci.com/gh/weaveworks/cortex/2700

**Comment by bboreham** [comment]
@tomwilkie yeah it can wait.  Maybe I'll just delete httpgrpc :wink:

**Comment by tomwilkie** [comment]
Meh, what did httpgrpc ever do for us?

**Comment by bboreham** [comment]
One approach would be to inspect the content-encoding of the response buffer and decompress if necessary.

Seems like a lot of work.

**Comment by tomwilkie** [comment]
> So this was actually caused by #898 

I don't see how - would you mind explaining?  AFAICT the Prometheus API Register has always compressed results.  I don't see how it ever worked...

**Comment by tomwilkie** [comment]
> One approach would be to inspect the content-encoding of the response buffer and decompress if necessary.

Not sure - everything should roundtrip.  If we return a non-200 compressed response from the querier, it gets propagated as a grpc error from querier -> authfe, then converted back to a http response and written (compression header and all) back to the client.

**Comment by bboreham** [comment]
> would you mind explaining

I haven't identified a specific code change, but we can make the issue come and go by switching to those querier versions noted above.

Even if round-trip was working, we'd still have a smaller problem that the error message is dumped into the OpenTracing span.

**Comment by bboreham** [comment]
I wonder if this relates to #780 which is also about corruption of response data.

**Comment by bboreham** [comment]
One difference between `query` and `query_range` is that the [Prometheus API ](https://github.com/prometheus/prometheus/blob/71855a22a456cfd25858ab3840fcdf8d590edd09/web/api/v1/api.go#L265-L266) turns a storage error into an internal error (500), whereas it doesn't do that on `query_range`.

Cortex does send back storage errors, so we should avoid that in cases like `exceeded maximum number of samples`, but there is a deeper problem: that Prometheus switch statement actually treats _all_ errors as storage errors, because a type assertion on an interface type is an 'implements' check, not an identical match.

Checking into where it breaks, I confirmed it returns 500s, but readable, `75de09a5` but returns compressed data in `57b71bbf`, so it broke in #910.  And if I update our front-end proxy to the same version of weaveworks/common the garbled data goes away, so I conclude the change to gRPC/proto generation was the culprit.

**Comment by bboreham** [comment]
Problems went away eventually after updating everything to the latest version after protobuf changes.
